using D2Tools.Types;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using GameOverlay.Drawing;

namespace D2Tools.Structs
{
    public enum D2Stat : short
    {
        STAT_INVALID = -1,
        STAT_STRENGTH = 0,                  // 000
        STAT_ENERGY,                        // 001
        STAT_DEXTERITY,                     // 002
        STAT_VITALITY,                      // 003
        STAT_STATPTS,                       // 004
        STAT_SKILLPTS,                      // 005
        STAT_HITPOINTS,                     // 006
        STAT_MAXHP,                         // 007
        STAT_MANA,                          // 008
        STAT_MAXMANA,                       // 009
        STAT_STAMINA,                       // 00A
        STAT_MAXSTAMINA,                    // 00B
        STAT_LEVEL,                         // 00C
        STAT_EXPERIENCE,                    // 00D
        STAT_GOLD,                          // 00E
        STAT_GOLDBANK,                      // 00F
        STAT_ITEM_ARMOR_PERCENT,            // 010
        STAT_ITEM_MAXDAMAGE_PERCENT,        // 011
        STAT_ITEM_MINDAMAGE_PERCENT,        // 012
        STAT_TOHIT,
        STAT_TOBLOCK,
        STAT_MINDAMAGE,
        STAT_MAXDAMAGE,
        STAT_SECONDARY_MINDAMAGE,
        STAT_SECONDARY_MAXDAMAGE,
        STAT_DAMAGEPERCENT,
        STAT_MANARECOVERY,
        STAT_MANARECOVERYBONUS,
        STAT_STAMINARECOVERYBONUS,
        STAT_LASTEXP,
        STAT_NEXTEXP,
        STAT_ARMORCLASS,
        STAT_ARMORCLASS_VS_MISSILE,
        STAT_ARMORCLASS_VS_HTH,
        STAT_NORMAL_DAMAGE_REDUCTION,
        STAT_MAGIC_DAMAGE_REDUCTION,
        STAT_DAMAGERESIST,
        STAT_MAGICRESIST,
        STAT_MAXMAGICRESIST,
        STAT_FIRERESIST,
        STAT_MAXFIRERESIST,
        STAT_LIGHTRESIST,
        STAT_MAXLIGHTRESIST,
        STAT_COLDRESIST,
        STAT_MAXCOLDRESIST,
        STAT_POISONRESIST,
        STAT_MAXPOISONRESIST,
        STAT_DAMAGEAURA,
        STAT_FIREMINDAM,
        STAT_FIREMAXDAM,
        STAT_LIGHTMINDAM,
        STAT_LIGHTMAXDAM,
        STAT_MAGICMINDAM,
        STAT_MAGICMAXDAM,
        STAT_COLDMINDAM,
        STAT_COLDMAXDAM,
        STAT_COLDLENGTH,
        STAT_POISONMINDAM,
        STAT_POISONMAXDAM,
        STAT_POISONLENGTH,
        STAT_LIFEDRAINMINDAM,
        STAT_LIFEDRAINMAXDAM,
        STAT_MANADRAINMINDAM,
        STAT_MANADRAINMAXDAM,
        STAT_STAMDRAINMINDAM,
        STAT_STAMDRAINMAXDAM,
        STAT_STUNLENGTH,
        STAT_VELOCITYPERCENT,
        STAT_ATTACKRATE,
        STAT_OTHER_ANIMRATE,
        STAT_QUANTITY,
        STAT_VALUE,
        STAT_DURABILITY,
        STAT_MAXDURABILITY,
        STAT_HPREGEN,
        STAT_ITEM_MAXDURABILITY_PERCENT,
        STAT_ITEM_MAXHP_PERCENT,
        STAT_ITEM_MAXMANA_PERCENT,
        STAT_ITEM_ATTACKERTAKESDAMAGE,
        STAT_ITEM_GOLDBONUS,
        STAT_ITEM_MAGICBONUS,
        STAT_ITEM_KNOCKBACK,
        STAT_ITEM_TIMEDURATION,
        STAT_ITEM_ADDCLASSSKILLS,
        STAT_UNSENTPARAM1,
        STAT_ITEM_ADDEXPERIENCE,
        STAT_ITEM_HEALAFTERKILL,
        STAT_ITEM_REDUCEDPRICES,
        STAT_ITEM_DOUBLEHERBDURATION,
        STAT_ITEM_LIGHTRADIUS,
        STAT_ITEM_LIGHTCOLOR,
        STAT_ITEM_REQ_PERCENT,
        STAT_ITEM_LEVELREQ,
        STAT_ITEM_FASTERATTACKRATE,
        STAT_ITEM_LEVELREQPCT,
        STAT_LASTBLOCKFRAME,
        STAT_ITEM_FASTERMOVEVELOCITY,
        STAT_ITEM_NONCLASSSKILL,
        STAT_STATE,
        STAT_ITEM_FASTERGETHITRATE,
        STAT_MONSTER_PLAYERCOUNT,
        STAT_SKILL_POISON_OVERRIDE_LENGTH,
        STAT_ITEM_FASTERBLOCKRATE,
        STAT_SKILL_BYPASS_UNDEAD,
        STAT_SKILL_BYPASS_DEMONS,
        STAT_ITEM_FASTERCASTRATE,
        STAT_SKILL_BYPASS_BEASTS,
        STAT_ITEM_SINGLESKILL,
        STAT_ITEM_RESTINPEACE,
        STAT_CURSE_RESISTANCE,
        STAT_ITEM_POISONLENGTHRESIST,
        STAT_ITEM_NORMALDAMAGE,
        STAT_ITEM_HOWL,
        STAT_ITEM_STUPIDITY,
        STAT_ITEM_DAMAGETOMANA,
        STAT_ITEM_IGNORETARGETAC,
        STAT_ITEM_FRACTIONALTARGETAC,
        STAT_ITEM_PREVENTHEAL,
        STAT_ITEM_HALFFREEZEDURATION,
        STAT_ITEM_TOHIT_PERCENT,
        STAT_ITEM_DAMAGETARGETAC,
        STAT_ITEM_DEMONDAMAGE_PERCENT,
        STAT_ITEM_UNDEADDAMAGE_PERCENT,
        STAT_ITEM_DEMON_TOHIT,
        STAT_ITEM_UNDEAD_TOHIT,
        STAT_ITEM_THROWABLE,
        STAT_ITEM_ELEMSKILL,
        STAT_ITEM_ALLSKILLS,
        STAT_ITEM_ATTACKERTAKESLIGHTDAMAGE,
        STAT_IRONMAIDEN_LEVEL,
        STAT_LIFETAP_LEVEL,
        STAT_THORNS_PERCENT,
        STAT_BONEARMOR,
        STAT_BONEARMORMAX,
        STAT_ITEM_FREEZE,
        STAT_ITEM_OPENWOUNDS,
        STAT_ITEM_CRUSHINGBLOW,
        STAT_ITEM_KICKDAMAGE,
        STAT_ITEM_MANAAFTERKILL,
        STAT_ITEM_HEALAFTERDEMONKILL,
        STAT_ITEM_EXTRABLOOD,
        STAT_ITEM_DEADLYSTRIKE,
        STAT_ITEM_ABSORBFIRE_PERCENT,
        STAT_ITEM_ABSORBFIRE,
        STAT_ITEM_ABSORBLIGHT_PERCENT,
        STAT_ITEM_ABSORBLIGHT,
        STAT_ITEM_ABSORBMAGIC_PERCENT,
        STAT_ITEM_ABSORBMAGIC,
        STAT_ITEM_ABSORBCOLD_PERCENT,
        STAT_ITEM_ABSORBCOLD,
        STAT_ITEM_SLOW,
        STAT_ITEM_AURA,
        STAT_ITEM_INDESCTRUCTIBLE,
        STAT_ITEM_CANNOTBEFROZEN,
        STAT_ITEM_STAMINADRAINPCT,
        STAT_ITEM_REANIMATE,
        STAT_ITEM_PIERCE,
        STAT_ITEM_MAGICARROW,
        STAT_ITEM_EXPLOSIVEARROW,
        STAT_ITEM_THROW_MINDAMAGE,
        STAT_ITEM_THROW_MAXDAMAGE,
        STAT_SKILL_HANDOFATHENA,
        STAT_SKILL_STAMINAPERCENT,
        STAT_SKILL_PASSIVE_STAMINAPERCENT,
        STAT_SKILL_CONCENTRATION,
        STAT_SKILL_ENCHANT,
        STAT_SKILL_PIERCE,
        STAT_SKILL_CONVICTION,
        STAT_SKILL_CHILLINGARMOR,
        STAT_SKILL_FRENZY,
        STAT_SKILL_DECREPIFY,
        STAT_SKILL_ARMOR_PERCENT,
        STAT_ALIGNMENT,
        STAT_TARGET0,
        STAT_TARGET1,
        STAT_GOLDLOST,
        STAT_CONVERSION_LEVEL,
        STAT_CONVERSION_MAXHP,
        STAT_UNIT_DOOVERLAY,
        STAT_ATTACK_VS_MONTYPE,
        STAT_DAMAGE_VS_MONTYPE,
        STAT_FADE,
        STAT_ARMOR_OVERRIDE_PERCENT,
        STAT_UNUSED183,
        STAT_UNUSED184,
        STAT_UNUSED185,
        STAT_UNUSED186,
        STAT_UNUSED187,
        STAT_ITEM_ADDSKILL_TAB,
        STAT_UNUSED189,
        STAT_UNUSED190,
        STAT_UNUSED191,
        STAT_UNUSED192,
        STAT_UNUSED193,
        STAT_ITEM_NUMSOCKETS,
        STAT_ITEM_SKILLONATTACK,
        STAT_ITEM_SKILLONKILL,
        STAT_ITEM_SKILLONDEATH,
        STAT_ITEM_SKILLONHIT,
        STAT_ITEM_SKILLONLEVELUP,
        STAT_UNUSED200,
        STAT_ITEM_SKILLONGETHIT,
        STAT_UNUSED202,
        STAT_UNUSED203,
        STAT_ITEM_CHARGED_SKILL,
        STAT_UNUSED204,
        STAT_UNUSED205,
        STAT_UNUSED206,
        STAT_UNUSED207,
        STAT_UNUSED208,
        STAT_UNUSED209,
        STAT_UNUSED210,
        STAT_UNUSED211,
        STAT_UNUSED212,
        STAT_ITEM_ARMOR_PERLEVEL,
        STAT_ITEM_ARMORPERCENT_PERLEVEL,
        STAT_ITEM_HP_PERLEVEL,
        STAT_ITEM_MANA_PERLEVEL,
        STAT_ITEM_MAXDAMAGE_PERLEVEL,
        STAT_ITEM_MAXDAMAGE_PERCENT_PERLEVEL,
        STAT_ITEM_STRENGTH_PERLEVEL,
        STAT_ITEM_DEXTERITY_PERLEVEL,
        STAT_ITEM_ENERGY_PERLEVEL,
        STAT_ITEM_VITALITY_PERLEVEL,
        STAT_ITEM_TOHIT_PERLEVEL,
        STAT_ITEM_TOHITPERCENT_PERLEVEL,
        STAT_ITEM_COLD_DAMAGEMAX_PERLEVEL,
        STAT_ITEM_FIRE_DAMAGEMAX_PERLEVEL,
        STAT_ITEM_LTNG_DAMAGEMAX_PERLEVEL,
        STAT_ITEM_POIS_DAMAGEMAX_PERLEVEL,
        STAT_ITEM_RESIST_COLD_PERLEVEL,
        STAT_ITEM_RESIST_FIRE_PERLEVEL,
        STAT_ITEM_RESIST_LTNG_PERLEVEL,
        STAT_ITEM_RESIST_POIS_PERLEVEL,
        STAT_ITEM_ABSORB_COLD_PERLEVEL,
        STAT_ITEM_ABSORB_FIRE_PERLEVEL,
        STAT_ITEM_ABSORB_LTNG_PERLEVEL,
        STAT_ITEM_ABSORB_POIS_PERLEVEL,
        STAT_ITEM_THORNS_PERLEVEL,
        STAT_ITEM_FIND_GOLD_PERLEVEL,
        STAT_ITEM_FIND_MAGIC_PERLEVEL,
        STAT_ITEM_REGENSTAMINA_PERLEVEL,
        STAT_ITEM_STAMINA_PERLEVEL,
        STAT_ITEM_DAMAGE_DEMON_PERLEVEL,
        STAT_ITEM_DAMAGE_UNDEAD_PERLEVEL,
        STAT_ITEM_TOHIT_DEMON_PERLEVEL,
        STAT_ITEM_TOHIT_UNDEAD_PERLEVEL,
        STAT_ITEM_CRUSHINGBLOW_PERLEVEL,
        STAT_ITEM_OPENWOUNDS_PERLEVEL,
        STAT_ITEM_KICK_DAMAGE_PERLEVEL,
        STAT_ITEM_DEADLYSTRIKE_PERLEVEL,
        STAT_ITEM_FIND_GEMS_PERLEVEL,
        STAT_ITEM_REPLENISH_DURABILITY,
        STAT_ITEM_REPLENISH_QUANTITY,
        STAT_ITEM_EXTRA_STACK,
        STAT_ITEM_FIND_ITEM,
        STAT_ITEM_SLASH_DAMAGE,
        STAT_ITEM_SLASH_DAMAGE_PERCENT,
        STAT_ITEM_CRUSH_DAMAGE,
        STAT_ITEM_CRUSH_DAMAGE_PERCENT,
        STAT_ITEM_THRUST_DAMAGE,
        STAT_ITEM_THRUST_DAMAGE_PERCENT,
        STAT_ITEM_ABSORB_SLASH,
        STAT_ITEM_ABSORB_CRUSH,
        STAT_ITEM_ABSORB_THRUST,
        STAT_ITEM_ABSORB_SLASH_PERCENT,
        STAT_ITEM_ABSORB_CRUSH_PERCENT,
        STAT_ITEM_ABSORB_THRUST_PERCENT,
        STAT_ITEM_ARMOR_BYTIME,
        STAT_ITEM_ARMORPERCENT_BYTIME,
        STAT_ITEM_HP_BYTIME,
        STAT_ITEM_MANA_BYTIME,
        STAT_ITEM_MAXDAMAGE_BYTIME,
        STAT_ITEM_MAXDAMAGE_PERCENT_BYTIME,
        STAT_ITEM_STRENGTH_BYTIME,
        STAT_ITEM_DEXTERITY_BYTIME,
        STAT_ITEM_ENERGY_BYTIME,
        STAT_ITEM_VITALITY_BYTIME,
        STAT_ITEM_TOHIT_BYTIME,
        STAT_ITEM_TOHITPERCENT_BYTIME,
        STAT_ITEM_COLD_DAMAGEMAX_BYTIME,
        STAT_ITEM_FIRE_DAMAGEMAX_BYTIME,
        STAT_ITEM_LTNG_DAMAGEMAX_BYTIME,
        STAT_ITEM_POIS_DAMAGEMAX_BYTIME,
        STAT_ITEM_RESIST_COLD_BYTIME,
        STAT_ITEM_RESIST_FIRE_BYTIME,
        STAT_ITEM_RESIST_LTNG_BYTIME,
        STAT_ITEM_RESIST_POIS_BYTIME,
        STAT_ITEM_ABSORB_COLD_BYTIME,
        STAT_ITEM_ABSORB_FIRE_BYTIME,
        STAT_ITEM_ABSORB_LTNG_BYTIME,
        STAT_ITEM_ABSORB_POIS_BYTIME,
        STAT_ITEM_FIND_GOLD_BYTIME,
        STAT_ITEM_FIND_MAGIC_BYTIME,
        STAT_ITEM_REGENSTAMINA_BYTIME,
        STAT_ITEM_STAMINA_BYTIME,
        STAT_ITEM_DAMAGE_DEMON_BYTIME,
        STAT_ITEM_DAMAGE_UNDEAD_BYTIME,
        STAT_ITEM_TOHIT_DEMON_BYTIME,
        STAT_ITEM_TOHIT_UNDEAD_BYTIME,
        STAT_ITEM_CRUSHINGBLOW_BYTIME,
        STAT_ITEM_OPENWOUNDS_BYTIME,
        STAT_ITEM_KICK_DAMAGE_BYTIME,
        STAT_ITEM_DEADLYSTRIKE_BYTIME,
        STAT_ITEM_FIND_GEMS_BYTIME,
        STAT_ITEM_PIERCE_COLD,
        STAT_ITEM_PIERCE_FIRE,
        STAT_ITEM_PIERCE_LTNG,
        STAT_ITEM_PIERCE_POIS,
        STAT_ITEM_DAMAGE_VS_MONSTER,
        STAT_ITEM_DAMAGE_PERCENT_VS_MONSTER,
        STAT_ITEM_TOHIT_VS_MONSTER,
        STAT_ITEM_TOHIT_PERCENT_VS_MONSTER,
        STAT_ITEM_AC_VS_MONSTER,
        STAT_ITEM_AC_PERCENT_VS_MONSTER,
        STAT_FIRELENGTH,
        STAT_BURNINGMIN,
        STAT_BURNINGMAX,
        STAT_PROGRESSIVE_DAMAGE,
        STAT_PROGRESSIVE_STEAL,
        STAT_PROGRESSIVE_OTHER,
        STAT_PROGRESSIVE_FIRE,
        STAT_PROGRESSIVE_COLD,
        STAT_PROGRESSIVE_LIGHTNING,
        STAT_ITEM_EXTRA_CHARGES,
        STAT_PROGRESSIVE_TOHIT,
        STAT_POISON_COUNT,
        STAT_DAMAGE_FRAMERATE,
        STAT_PIERCE_IDX,
        STAT_PASSIVE_FIRE_MASTERY,
        STAT_PASSIVE_LTNG_MASTERY,
        STAT_PASSIVE_COLD_MASTERY,
        STAT_PASSIVE_POIS_MASTERY,
        STAT_PASSIVE_FIRE_PIERCE,
        STAT_PASSIVE_LTNG_PIERCE,
        STAT_PASSIVE_COLD_PIERCE,
        STAT_PASSIVE_POIS_PIERCE,
        STAT_PASSIVE_CRITICAL_STRIKE,
        STAT_PASSIVE_DODGE,
        STAT_PASSIVE_AVOID,
        STAT_PASSIVE_EVADE,
        STAT_PASSIVE_WARMTH,
        STAT_PASSIVE_MASTERY_MELEE_TH,
        STAT_PASSIVE_MASTERY_MELEE_DMG,
        STAT_PASSIVE_MASTERY_MELEE_CRIT,
        STAT_PASSIVE_MASTERY_THROW_TH,
        STAT_PASSIVE_MASTERY_THROW_DMG,
        STAT_PASSIVE_MASTERY_THROW_CRIT,
        STAT_PASSIVE_WEAPONBLOCK,
        STAT_PASSIVE_SUMMON_RESIST,
        STAT_MODIFIERLIST_SKILL,
        STAT_MODIFIERLIST_LEVEL,
        STAT_LAST_SENT_HP_PCT,
        STAT_SOURCE_UNIT_TYPE,
        STAT_SOURCE_UNIT_ID,
        STAT_SHORTPARAM1,
        STAT_QUESTITEMDIFFICULTY,
        STAT_PASSIVE_MAG_MASTERY,
        STAT_PASSIVE_MAG_PIERCE,
    };
    
    public enum D2ItemLocation : uint
    {
        STASH = 0,
        EQUIPPED = 1,
        BELT = 2,
        GROUND = 3,
        CURSOR = 4,
        SOCKET = 6
    };

    public enum D2ItemLocationPanel : byte
    {
        MERCHANT = 1,
        INVENTORY = 0,
        CUBE = 3,
        STASH = 4,
        NONE = 255
    };

    public enum D2ItemEquipLocation : byte
    {
        NOT_EQUIPPED = 0,
        HEAD = 1,
        NECK = 2,
        TORSO = 3,
        HAND_RIGHT = 4,
        HAND_LEFT = 5,
        FINGER_RIGHT = 6,
        FINGER_LEFT = 7,
        WAIST = 8,
        FEET = 9,
        HANDS = 10,
        ALT_HAND_RIGHT = 11,
        ALT_HAND_LEFT = 12,
    };

    public enum D2ItemType : uint
    {
        ARMOR = 1,
        SHIELD = 2,
        WEAPON = 3,
        OTHER = 4
    }
    
    public enum D2ItemIdentified : byte
    {
        NON_IDENTIFIED = 0,
        IDENTIFIED = 1,
    }

    public enum D2ItemRarity : byte
    {
        NONE = 0,
        LOW_QUALITY = 1,
        NORMAL = 2,
        HIGH_QUALITY = 3,
        MAGIC = 4,
        SET = 5,
        RARE = 6,
        UNIQUE = 7,
        CRAFTED = 8,
        TEMPERED, // Was never actually enabled in an official release
    }
    
    [StructLayout(LayoutKind.Explicit)]
    public readonly struct D2StatValueData
    {
        [FieldOffset(0x0)] public readonly ushort Layer;
        [FieldOffset(0x2)] public readonly D2Stat Stat;
        [FieldOffset(0x4)] public readonly int Value;
    }

    [StructLayout(LayoutKind.Explicit)]
    public readonly struct D2StatArrayData
    {
        [FieldOffset(0x0)] public readonly IntPtr FirstStatPtr;
        [FieldOffset(0x8)] public readonly ulong Size;
        [FieldOffset(0x10)] public readonly ulong Capacity;
    }

    [StructLayout(LayoutKind.Explicit)]
    public readonly struct D2StatListData
    {
        [FieldOffset(0x8)] public readonly uint OwnerType;
        [FieldOffset(0xC)] public readonly uint OwnerId;
        [FieldOffset(0x1C)] public readonly uint Flags;
        [FieldOffset(0x80)] public readonly D2StatArrayData Stats;
    }

    [StructLayout(LayoutKind.Explicit)]
    public struct D2ItemData
    {
        [FieldOffset(0x00)] public D2UnitType ObjectType;
        [FieldOffset(0x0C)] public D2ItemLocation Location; // GROUND
    }

    [StructLayout(LayoutKind.Explicit)]
    public struct D2ItemUnitData // pUnitData + n
    {
        [FieldOffset(0x00)] public D2ItemRarity Rarity;
        [FieldOffset(0x18)] private byte _itemIdentified;
        [FieldOffset(0x19)] private byte _itemFlags1; // socketed
        [FieldOffset(0x1A)] private byte _itemFlags2; // etheral
        [FieldOffset(0x50)] public D2ItemEquipLocation EquipLocation;
        [FieldOffset(0x51)] public D2ItemLocationPanel StoreLocation;

        public D2ItemIdentified Identified => (D2ItemIdentified)(_itemIdentified >> 4);
        public bool Etheral => (_itemFlags2 & (1 << 6)) != 0;
        public bool Socketed => (_itemFlags1 & (1 << 3)) != 0;
        public bool New => (_itemFlags1 & (1 << 5)) != 0;

        public bool IsIdentified => Identified == D2ItemIdentified.IDENTIFIED;
    }

    [StructLayout(LayoutKind.Explicit)]
    public struct D2ItemInventoryData // pInventory + n
    {
        [FieldOffset(0x4C)] private byte _socketsFilled;

        public int SocketsFilled => _socketsFilled;
    }
    
    public class BaseD2
    {
        public Pointers Pointers;

        public D2UnitAnyType Unit;

        public override string ToString()
        {
            StringBuilder stringBuilder = new StringBuilder();

            stringBuilder.AppendLine(Pointers.ToString());
            stringBuilder.AppendLine("UID: " + Unit.UID);
            stringBuilder.AppendLine("TXTID: " + Unit.TXTID);
            stringBuilder.AppendLine(Unit.Position.ToString());

            return stringBuilder.ToString();
        }
    }

    public class ItemD2 : BaseD2
    {
        public static Dictionary<D2ItemRarity, Color> ItemRarityColors = new Dictionary<D2ItemRarity, Color>()
        {
            { D2ItemRarity.NORMAL, new Color(240, 240, 240) },
            { D2ItemRarity.HIGH_QUALITY, new Color(240, 240, 240) },
            { D2ItemRarity.LOW_QUALITY, new Color(99, 99, 99) },
            { D2ItemRarity.MAGIC, new Color(110, 110, 255) },
            { D2ItemRarity.RARE, new Color(255, 255, 100) },
            { D2ItemRarity.SET, new Color(0, 252, 0) },
            { D2ItemRarity.UNIQUE, new Color(199, 179, 119) },
            { D2ItemRarity.CRAFTED, new Color(255, 168, 0) },
            { D2ItemRarity.NONE, new Color(0, 0, 0) },
        };

        public static Dictionary<uint, string> ItemIDs = new Dictionary<uint, string>()
        {
            { 0, "Hand Axe" },
            { 1, "Axe" },
            { 2, "Double Axe" },
            { 3, "Military Pick" },
            { 4, "War Axe" },
            { 5, "Large Axe" },
            { 6, "Broad Axe" },
            { 7, "Battle Axe" },
            { 8, "Great Axe" },
            { 9, "Giant Axe" },
            { 10, "Wand" },
            { 11, "Yew Wand" },
            { 12, "Bone Wand" },
            { 13, "Grim Wand" },
            { 14, "Club" },
            { 15, "Scepter" },
            { 16, "Grand Scepter" },
            { 17, "War Scepter" },
            { 18, "Spiked Club" },
            { 19, "Mace" },
            { 20, "Morning Star" },
            { 21, "Flail" },
            { 22, "War Hammer" },
            { 23, "Maul" },
            { 24, "Great Maul" },
            { 25, "Short Sword" },
            { 26, "Scimitar" },
            { 27, "Sabre" },
            { 28, "Falchion" },
            { 29, "Crystal Sword" },
            { 30, "Broad Sword" },
            { 31, "Long Sword" },
            { 32, "War Sword" },
            { 33, "Two-handed Sword" },
            { 34, "Claymore" },
            { 35, "Giant Sword" },
            { 36, "Bastard Sword" },
            { 37, "Flamberge" },
            { 38, "Great Sword" },
            { 39, "Dagger" },
            { 40, "Dirk" },
            { 41, "Kris" },
            { 42, "Blade" },
            { 43, "Throwing Knife" },
            { 44, "Throwing Axe" },
            { 45, "Balanced Knife" },
            { 46, "Balanced Axe" },
            { 47, "Javelin" },
            { 48, "Pilum" },
            { 49, "Short Spear" },
            { 50, "Glaive" },
            { 51, "Throwing Spear" },
            { 52, "Spear" },
            { 53, "Trident" },
            { 54, "Brandistock" },
            { 55, "Spetum" },
            { 56, "Pike" },
            { 57, "Bardiche" },
            { 58, "Voulge" },
            { 59, "Scythe" },
            { 60, "Poleaxe" },
            { 61, "Halberd" },
            { 62, "War Scythe" },
            { 63, "Short Staff" },
            { 64, "Long Staff" },
            { 65, "Gnarled Staff" },
            { 66, "Battle Staff" },
            { 67, "War Staff" },
            { 68, "Short Bow" },
            { 69, "Hunter's Bow" },
            { 70, "Long Bow" },
            { 71, "Composite Bow" },
            { 72, "Short Battle Bow" },
            { 73, "Long Battle ow" },
            { 74, "Short War Bow" },
            { 75, "Long War Bow" },
            { 76, "Light CrossBow" },
            { 77, "CrossBow" },
            { 78, "Heavy CrossBow" },
            { 79, "Repeating CrossBow" },
            { 80, "Rancid Gas Potion" },
            { 81, "Oil Potion" },
            { 82, "Choking Gas Potion" },
            { 83, "Exploding Potion" },
            { 84, "Strangling Gas Potion" },
            { 85, "Fulminating Potion" },
            { 86, "Decoy Gidbinn" },
            { 87, "The Gidbinn" },
            { 88, "Wirt's Leg" },
            { 89, "Horadric Malus" },
            { 90, "Hellforge Hammer" },
            { 91, "Horadric Staff" },
            { 92, "Shaft Of The Horadric Staff" },
            { 93, "Hatchet" },
            { 94, "Cleaver" },
            { 95, "Twin Axe" },
            { 96, "Crowbill" },
            { 97, "Naga" },
            { 98, "Military Axe" },
            { 99, "Bearded Axe" },
            { 100, "Tabar" },
            { 101, "Gothic Axe" },
            { 102, "Ancient Axe" },
            { 103, "Burnt Wand" },
            { 104, "Petrified Wand" },
            { 105, "Tomb Wand" },
            { 106, "Grave Wand" },
            { 107, "Cudgel" },
            { 108, "Rune Scepter" },
            { 109, "Holy Water Sprinkler" },
            { 110, "Divine Scepter" },
            { 111, "Barbed Club" },
            { 112, "Flanged Mace" },
            { 113, "Jagged Star" },
            { 114, "Knout" },
            { 115, "Battle Hammer" },
            { 116, "War Club" },
            { 117, "Martel De Fer" },
            { 118, "Gladius" },
            { 119, "Cutlass" },
            { 120, "Shamshir" },
            { 121, "Tulwar" },
            { 122, "Dimensional Blade" },
            { 123, "Battle Sword" },
            { 124, "Rune Sword" },
            { 125, "Ancient Sword" },
            { 126, "Espandon" },
            { 127, "Dacian Falx" },
            { 128, "Tusk Sword" },
            { 129, "Gothic Sword" },
            { 130, "Zweihander" },
            { 131, "Executioner Sword" },
            { 132, "Poignard" },
            { 133, "Rondel" },
            { 134, "Cinquedeas" },
            { 135, "Stiletto" },
            { 136, "Battle Dart" },
            { 137, "Francisca" },
            { 138, "Wardart" },
            { 139, "Hurlbat" },
            { 140, "War Javelin" },
            { 141, "Great Pilum" },
            { 142, "Simbilan" },
            { 143, "Spiculum" },
            { 144, "Harpoon" },
            { 145, "War Spear" },
            { 146, "Fuscina" },
            { 147, "Warfork" },
            { 148, "Yari" },
            { 149, "Lance" },
            { 150, "Lochaber Axe" },
            { 151, "Bill" },
            { 152, "Battle Scythe" },
            { 153, "Partizan" },
            { 154, "Bec-De-Corbin" },
            { 155, "Grim Scythe" },
            { 156, "Jo Staff" },
            { 157, "Quarter Staff" },
            { 158, "Cedar Staff" },
            { 159, "Gothic Staff" },
            { 160, "Rune Staff" },
            { 161, "Edge Bow" },
            { 162, "Razor Bow" },
            { 163, "Cedar Bow" },
            { 164, "Double Bow" },
            { 165, "Short Siege Bow" },
            { 166, "Large Siege Bow" },
            { 167, "Rune Bow" },
            { 168, "Gothic Bow" },
            { 169, "Arbalest" },
            { 170, "Siege Crossbow" },
            { 171, "Ballista" },
            { 172, "Chu-ko-nu" },
            { 173, "Khalim's Flail" },
            { 174, "Khalim's Will" },
            { 175, "Katar" },
            { 176, "Wrist Blade" },
            { 177, "Hatchet Hands" },
            { 178, "Cestus" },
            { 179, "Claws" },
            { 180, "Blade Talons" },
            { 181, "Scissors Katar" },
            { 182, "Quhab" },
            { 183, "Wrist Spike" },
            { 184, "Fascia" },
            { 185, "Hand Scythe" },
            { 186, "Greater Claws" },
            { 187, "Greater Talons" },
            { 188, "Scissors Quhab" },
            { 189, "Suwayyah" },
            { 190, "Wrist Sword" },
            { 191, "War Fist" },
            { 192, "Battle Cestus" },
            { 193, "Feral Claws" },
            { 194, "Runic Talons" },
            { 195, "Scissors Suwayyah" },
            { 196, "Tomahawk" },
            { 197, "Small Crescent" },
            { 198, "Ettin Axe" },
            { 199, "War Spike" },
            { 200, "Berserker Axe" },
            { 201, "Feral Axe" },
            { 202, "Silver-Edged Axe" },
            { 203, "Decapitator" },
            { 204, "Champion Axe" },
            { 205, "Glorious Axe" },
            { 206, "Polished Wand" },
            { 207, "Ghost Wand" },
            { 208, "Lich Wand" },
            { 209, "Unearthed Wand" },
            { 210, "Truncheon" },
            { 211, "Mighty Scepter" },
            { 212, "Seraphrod" },
            { 213, "Caduceus" },
            { 214, "Tyrant Club" },
            { 215, "Reinforced mace" },
            { 216, "Devil Star" },
            { 217, "Scourge" },
            { 218, "Legendary Mallet" },
            { 219, "Ogre Maul" },
            { 220, "Thunder Maul" },
            { 221, "Falcata" },
            { 222, "Ataghan" },
            { 223, "Elegant Blade" },
            { 224, "Hydra Edge" },
            { 225, "Phase Blade" },
            { 226, "Conquest Sword" },
            { 227, "Cryptic Sword" },
            { 228, "Mythical Sword" },
            { 229, "Legend Sword" },
            { 230, "Highland Blade" },
            { 231, "Balrog Blade" },
            { 232, "Champion Sword" },
            { 233, "Colossus Sword" },
            { 234, "Colossus Blade" },
            { 235, "Bone Knife" },
            { 236, "Mithril Point" },
            { 237, "Fanged Knife" },
            { 238, "Legend Spike" },
            { 239, "Flying Knife" },
            { 240, "Flying Axe" },
            { 241, "Winged Knife" },
            { 242, "Winged Axe" },
            { 243, "Hyperion Javelin" },
            { 244, "Stygian Pilum" },
            { 245, "Balrog Spear" },
            { 246, "Ghost Glaive" },
            { 247, "Winged Harpoon" },
            { 248, "Hyperion Spear" },
            { 249, "Stygian Pike" },
            { 250, "Mancatcher" },
            { 251, "Ghost Spear" },
            { 252, "War Pike" },
            { 253, "Ogre Axe" },
            { 254, "Colossus Voulge" },
            { 255, "Thresher" },
            { 256, "Cryptic Axe" },
            { 257, "Great Poleaxe" },
            { 258, "Giant Thresher" },
            { 259, "Walking Stick" },
            { 260, "Stalagmite" },
            { 261, "Elder Staff" },
            { 262, "Shillelagh" },
            { 263, "Archon Staff" },
            { 264, "Spider Bow" },
            { 265, "Blade Bow" },
            { 266, "Shadow Bow" },
            { 267, "Great Bow" },
            { 268, "Diamond Bow" },
            { 269, "Crusader Bow" },
            { 270, "Ward Bow" },
            { 271, "Hydra Bow" },
            { 272, "Pellet Bow" },
            { 273, "Gorgon Crossbow" },
            { 274, "Colossus Crossbow" },
            { 275, "Demon CrossBow" },
            { 276, "Eagle Orb" },
            { 277, "Sacred Globe" },
            { 278, "Smoked Sphere" },
            { 279, "Clasped Orb" },
            { 280, "Jared's Stone" },
            { 281, "Stag Bow" },
            { 282, "Reflex Bow" },
            { 283, "Maiden Spear" },
            { 284, "Maiden Pike" },
            { 285, "Maiden Javelin" },
            { 286, "Glowing Orb" },
            { 287, "Crystalline Globe" },
            { 288, "Cloudy Sphere" },
            { 289, "Sparkling Ball" },
            { 290, "Swirling Crystal" },
            { 291, "Ashwood Bow" },
            { 292, "Ceremonial Bow" },
            { 293, "Ceremonial Spear" },
            { 294, "Ceremonial Pike" },
            { 295, "Ceremonial Javelin" },
            { 296, "Heavenly Stone" },
            { 297, "Eldritch Orb" },
            { 298, "Demon Heart" },
            { 299, "Vortex Orb" },
            { 300, "Dimensional Shard" },
            { 301, "Matriarchal Bow" },
            { 302, "Grandmatron Bow" },
            { 303, "Matriarchal Spear" },
            { 304, "Matriarchal Pike" },
            { 305, "Matriarchal Javelin" },
            { 306, "Cap" },
            { 307, "Skull Cap" },
            { 308, "Helm" },
            { 309, "Full Helm" },
            { 310, "Great Helm" },
            { 311, "Crown" },
            { 312, "Mask" },
            { 313, "Quilted Armor" },
            { 314, "Leather Armor" },
            { 315, "Hardleather Armor" },
            { 316, "Studded Leather" },
            { 317, "Ring Mail" },
            { 318, "Scale Mail" },
            { 319, "Chain Mail" },
            { 320, "Breast Plate" },
            { 321, "Splint Mail" },
            { 322, "Plate Mail" },
            { 323, "Field Plate" },
            { 324, "Gothic Plate" },
            { 325, "Full Plate Mail" },
            { 326, "Ancient Armor" },
            { 327, "Light Plate" },
            { 328, "Buckler" },
            { 329, "Small Shield" },
            { 330, "Large Shield" },
            { 331, "Kite Shield" },
            { 332, "Tower Shield" },
            { 333, "Gothic Shield" },
            { 334, "Leather Gloves" },
            { 335, "Heavy Gloves" },
            { 336, "Chain Gloves" },
            { 337, "Light Gauntlets" },
            { 338, "Gauntlets" },
            { 339, "Boots" },
            { 340, "Heavy Boots" },
            { 341, "Chain Boots" },
            { 342, "Light Plated Boots" },
            { 343, "Greaves" },
            { 344, "Sash" },
            { 345, "Light Belt" },
            { 346, "Belt" },
            { 347, "Heavy Belt" },
            { 348, "Plated Belt" },
            { 349, "Bone Helm" },
            { 350, "Bone Shield" },
            { 351, "Spiked Shield" },
            { 352, "War Hat" },
            { 353, "Sallet" },
            { 354, "Casque" },
            { 355, "Basinet" },
            { 356, "Winged Helm" },
            { 357, "Grand Crown" },
            { 358, "Death Mask" },
            { 359, "Ghost Armor" },
            { 360, "Serpentskin Armor" },
            { 361, "Demonhide Armor" },
            { 362, "Trellised Armor" },
            { 363, "Linked Mail" },
            { 364, "Tigulated Mail" },
            { 365, "Mesh Armor" },
            { 366, "Cuirass" },
            { 367, "Russet Armor" },
            { 368, "Templar Coat" },
            { 369, "Sharktooth Armor" },
            { 370, "Embossed Plate" },
            { 371, "Chaos Armor" },
            { 372, "Ornate Plate" },
            { 373, "Mage Plate" },
            { 374, "Defender" },
            { 375, "Round Shield" },
            { 376, "Scutum" },
            { 377, "Dragon Shield" },
            { 378, "Pavise" },
            { 379, "Ancient Shield" },
            { 380, "Demonhide Gloves" },
            { 381, "Sharkskin Gloves" },
            { 382, "Heavy Bracers" },
            { 383, "Battle Gauntlets" },
            { 384, "War Gauntlets" },
            { 385, "Demonhide Boots" },
            { 386, "Sharkskin Boots" },
            { 387, "Mesh Boots" },
            { 388, "Battle Boots" },
            { 389, "War Boots" },
            { 390, "Demonhide Sash" },
            { 391, "Sharkskin Belt" },
            { 392, "Mesh Belt" },
            { 393, "Battle Belt" },
            { 394, "War Belt" },
            { 395, "Grim Helm" },
            { 396, "Grim Shield" },
            { 397, "Barbed Shield" },
            { 398, "Wolf Head" },
            { 399, "Hawk Helm" },
            { 400, "Antlers" },
            { 401, "Falcon Mask" },
            { 402, "Spirit Mask" },
            { 403, "Jawbone Cap" },
            { 404, "Fanged Helm" },
            { 405, "Horned Helm" },
            { 406, "Assault Helmet" },
            { 407, "Avenger Guard" },
            { 408, "Targe" },
            { 409, "Rondache" },
            { 410, "Heraldic Shield" },
            { 411, "Aerin Shield" },
            { 412, "Crown Shield" },
            { 413, "Preserved Head" },
            { 414, "Zombie Head" },
            { 415, "Unraveller Head" },
            { 416, "Gargoyle Head" },
            { 417, "Demon Head" },
            { 418, "Circlet" },
            { 419, "Coronet" },
            { 420, "Tiara" },
            { 421, "Diadem" },
            { 422, "Shako" },
            { 423, "Hydra Skull" },
            { 424, "Armet" },
            { 425, "Giant Conch" },
            { 426, "Spired Helm" },
            { 427, "Corona" },
            { 428, "Demon Head" },
            { 429, "Dusk Shroud" },
            { 430, "Wyrmhide" },
            { 431, "Scarab Husk" },
            { 432, "Wire Fleece" },
            { 433, "Diamond Mail" },
            { 434, "Loricated Mail" },
            { 435, "Bone Weave" },
            { 436, "Great Hauberk" },
            { 437, "Balrog Skin" },
            { 438, "Hellforge Plate" },
            { 439, "Kraken Shell" },
            { 440, "Lacquered Plate" },
            { 441, "Shadow Plate" },
            { 442, "Sacred Armor" },
            { 443, "Archon Plate" },
            { 444, "Heater" },
            { 445, "Luna" },
            { 446, "Hyperion" },
            { 447, "Monarch" },
            { 448, "Aegis" },
            { 449, "Ward" },
            { 450, "Bramble Mitts" },
            { 451, "Vampirebone Gloves" },
            { 452, "Vambraces" },
            { 453, "Crusader Gauntlets" },
            { 454, "Ogre Gauntlets" },
            { 455, "Wyrmhide Boots" },
            { 456, "Scarabshell Boots" },
            { 457, "Boneweave Boots" },
            { 458, "Mirrored Boots" },
            { 459, "Myrmidon Greaves" },
            { 460, "Spiderweb Sash" },
            { 461, "Vampirefang Belt" },
            { 462, "Mithril Coil" },
            { 463, "Troll Belt" },
            { 464, "Colossus Girdle" },
            { 465, "Bone Visage" },
            { 466, "Troll Nest" },
            { 467, "Blade Barrier" },
            { 468, "Alpha Helm" },
            { 469, "Griffon Headdress" },
            { 470, "Hunter's Guise" },
            { 471, "Sacred Feathers" },
            { 472, "Totemic Mask" },
            { 473, "Jawbone Visor" },
            { 474, "Lion Helm" },
            { 475, "Rage Mask" },
            { 476, "Savage Helmet" },
            { 477, "Slayer Guard" },
            { 478, "Akaran Targe" },
            { 479, "Akaran Rondache" },
            { 480, "Protector Shield" },
            { 481, "Gilded Shield" },
            { 482, "Royal Shield" },
            { 483, "Mummified Trophy" },
            { 484, "Fetish Trophy" },
            { 485, "Sexton Trophy" },
            { 486, "Cantor Trophy" },
            { 487, "Hierophant Trophy" },
            { 488, "Blood Spirit" },
            { 489, "Sun Spirit" },
            { 490, "Earth Spirit" },
            { 491, "Sky Spirit" },
            { 492, "Dream Spirit" },
            { 493, "Carnage Helm" },
            { 494, "Fury Visor" },
            { 495, "Destroyer Helm" },
            { 496, "Conqueror Crown" },
            { 497, "Guardian Crown" },
            { 498, "Sacred Targe" },
            { 499, "Sacred Rondache" },
            { 500, "Kurast Shield" },
            { 501, "Zakarum Shield" },
            { 502, "Vortex Shield" },
            { 503, "Minion Skull" },
            { 504, "Hellspawn Skull" },
            { 505, "Overseer Skull" },
            { 506, "Succubus Skull" },
            { 507, "Bloodlord Skull" },
            { 508, "Elixir" },
            { 509, "INVALID" },
            { 510, "INVALID" },
            { 511, "INVALID" },
            { 512, "INVALID" },
            { 513, "Stamina Potion" },
            { 514, "Antidote Potion" },
            { 515, "Rejuvenation Potion" },
            { 516, "Full Rejuvenation Potion" },
            { 517, "Thawing Potion" },
            { 518, "Tome Of Town Portal" },
            { 519, "Tome Of Identify" },
            { 520, "Amulet" },
            { 521, "Top Of The Horadric Staff" },
            { 522, "Ring" },
            { 523, "Gold" },
            { 524, "Scroll Of Inifuss" },
            { 525, "Key To The Cairn Stones" },
            { 526, "Arrows" },
            { 527, "Torch" },
            { 528, "Bolts" },
            { 529, "Scroll Of Town Portal" },
            { 530, "Scroll Of Identify" },
            { 531, "Heart" },
            { 532, "Brain" },
            { 533, "Jawbone" },
            { 534, "Eye" },
            { 535, "Horn" },
            { 536, "Tail" },
            { 537, "Flag" },
            { 538, "Fang" },
            { 539, "Quill" },
            { 540, "Soul" },
            { 541, "Scalp" },
            { 542, "Spleen" },
            { 543, "Key" },
            { 544, "The Black Tower Key" },
            { 545, "Potion Of Life" },
            { 546, "A Jade Figurine" },
            { 547, "The Golden Bird" },
            { 548, "Lam Esen's Tome" },
            { 549, "Horadric Cube" },
            { 550, "Horadric Scroll" },
            { 551, "Mephisto's Soulstone" },
            { 552, "Book Of Skill" },
            { 553, "Khalim's Eye" },
            { 554, "Khalim's Heart" },
            { 555, "Khalim's Brain" },
            { 556, "Ear" },
            { 557, "Chipped Amethyst" },
            { 558, "Flawed Amethyst" },
            { 559, "Amethyst" },
            { 560, "Flawless Amethyst" },
            { 561, "Perfect Amethyst" },
            { 562, "Chipped Topaz" },
            { 563, "Flawed Topaz" },
            { 564, "Topaz" },
            { 565, "Flawless Topaz" },
            { 566, "Perfect Topaz" },
            { 567, "Chipped Sapphire" },
            { 568, "Flawed Sapphire" },
            { 569, "Sapphire" },
            { 570, "Flawless Sapphire" },
            { 571, "Perfect Sapphire" },
            { 572, "Chipped Emerald" },
            { 573, "Flawed Emerald" },
            { 574, "Emerald" },
            { 575, "Flawless Emerald" },
            { 576, "Perfect Emerald" },
            { 577, "Chipped Ruby" },
            { 578, "Flawed Ruby" },
            { 579, "Ruby" },
            { 580, "Flawless Ruby" },
            { 581, "Perfect Ruby" },
            { 582, "Chipped Diamond" },
            { 583, "Flawed Diamond" },
            { 584, "Diamond" },
            { 585, "Flawless Diamond" },
            { 586, "Perfect Diamond" },
            { 587, "Minor Healing Potion" },
            { 588, "Light Healing Potion" },
            { 589, "Healing Potion" },
            { 590, "Greater Healing Potion" },
            { 591, "Super Healing Potion" },
            { 592, "Minor Mana Potion" },
            { 593, "Light Mana Potion" },
            { 594, "Mana Potion" },
            { 595, "Greater Mana Potion" },
            { 596, "Super Mana Potion" },
            { 597, "Chipped Skull" },
            { 598, "Flawed Skull" },
            { 599, "Skull" },
            { 600, "Flawless Skull" },
            { 601, "Perfect Skull" },
            { 602, "Herb" },
            { 603, "Small Charm" },
            { 604, "Large Charm" },
            { 605, "Grand Charm" },
            { 606, "? " },
            { 607, "? " },
            { 608, "? " },
            { 609, "? " },
            { 610, "El Rune" },
            { 611, "Eld Rune" },
            { 612, "Tir Rune" },
            { 613, "Nef Rune" },
            { 614, "Eth Rune" },
            { 615, "Ith Rune" },
            { 616, "Tal Rune" },
            { 617, "Ral Rune" },
            { 618, "Ort Rune" },
            { 619, "Thul Rune" },
            { 620, "Amn Rune" },
            { 621, "Sol Rune" },
            { 622, "Shael Rune" },
            { 623, "Dol Rune" },
            { 624, "Hel Rune" },
            { 625, "Io Rune" },
            { 626, "Lum Rune" },
            { 627, "Ko Rune" },
            { 628, "Fal Rune" },
            { 629, "Lem Rune" },
            { 630, "Pul Rune" },
            { 631, "Um Rune" },
            { 632, "Mal Rune" },
            { 633, "Ist Rune" },
            { 634, "Gul Rune" },
            { 635, "Vex Rune" },
            { 636, "Ohm Rune" },
            { 637, "Lo Rune" },
            { 638, "Sur Rune" },
            { 639, "Ber Rune" },
            { 640, "Jah Rune" },
            { 641, "Cham Rune" },
            { 642, "Zod Rune" },
            { 643, "Jewel" },
            { 644, "Malah's Potion" },
            { 645, "Scroll Of Knowledge" },
            { 646, "Scroll Of Resistance" },
            { 647, "Key Of Terror" },
            { 648, "Key Of Hate" },
            { 649, "Key Of Destruction" },
            { 650, "Diablo's Horn" },
            { 651, "Baal's Eye" },
            { 652, "Mephisto's Brain" },
            { 653, "Token of Absolution" },
            { 654, "Twisted Essence Of Suffering" },
            { 655, "Charged Essence Of Hatred" },
            { 656, "Burning Essence Of Terror" },
            { 657, "Festering Essence Of Destruction" },
            { 658, "Standard Of Heroes" }
        };

        public string Name
        {
            get
            {
                bool existID = ItemIDs.TryGetValue(Unit.TXTID, out string nameById);
                return existID ? nameById : "?" + Unit.TXTID;
            }
        }

        private static HashSet<uint> NonSimpleItems = new HashSet<uint>()
        {
            520, 522, 527, 603, 604, 605, 643
        };

        public bool IsSimple
        {
            get
            {
                uint id = Unit.TXTID;

                return id > 507 && !NonSimpleItems.Contains(id);
            }
        }

        public bool IsRune => Unit.TXTID > 609 && Unit.TXTID < 643;

        public D2ItemData ItemData;
        public D2ItemInventoryData ItemInventoryData;
        public D2ItemUnitData ItemUnitData;

        public D2StatValueData[] Stats;
        public D2StatListData StatsListData;

        public bool TryGetStat(D2Stat stat, out int statValue)
        {
            if (Stats == null)
            {
                statValue = 0;
                return false;
            }
            
            for (int i = 0; i < Stats.Length; i++)
            {
                if (Stats[i].Stat != stat) continue;
                
                statValue = Stats[i].Value;
                return true;
            }
            
            statValue = 0;
            return false;
        }

        public override string ToString()
        {
            StringBuilder stringBuilder = new StringBuilder();

            stringBuilder.AppendLine(base.ToString());

            stringBuilder.AppendLine("ItemName: " + Name);
            stringBuilder.AppendLine("Rarity: " + ItemUnitData.Rarity);
            stringBuilder.AppendLine("Location: " + ItemData.Location);
            stringBuilder.AppendLine("StoreLocation: " + ItemUnitData.StoreLocation);
            stringBuilder.AppendLine("EquipLocation: " + ItemUnitData.EquipLocation);
            stringBuilder.AppendLine("Identified: " + ItemUnitData.Identified);
            stringBuilder.AppendLine("Etheral: " + ItemUnitData.Etheral);
            stringBuilder.AppendLine("Socketed: " + ItemUnitData.Socketed);
            if (ItemUnitData.Socketed) stringBuilder.AppendLine("Sockets Filled: " + ItemInventoryData.SocketsFilled);

            stringBuilder.AppendLine("+ Stats:");

            foreach (var stat in Stats)
                stringBuilder.AppendLine(stat.Stat + " " + stat.Value);

            return stringBuilder.ToString();

        }
    }
}
